/* eslint-disable no-magic-numbers */
/* eslint-disable complexity */
/* eslint-disable max-lines-per-function */
export function iconForWeatherCode(code: number): string {
  switch (code) {
    case 395:
      return 'wi-day-snow-thunderstorm';
    case 392:
      return 'wi-day-snow-thunderstorm';
    case 389:
      return 'wi-day-thunderstorm';
    case 386:
      return 'wi-day-storm-showers';
    case 377:
      return 'wi-day-hail';
    case 374:
      return 'wi-day-sleet';
    case 371:
      return 'wi-day-snow';
    case 368:
      return 'wi-day-snow';
    case 365:
      return 'wi-day-sleet-storm';
    case 362:
      return 'wi-day-sleet';
    case 359:
      return 'wi-day-rain';
    case 356:
      return 'wi-day-showers';
    case 353:
      return 'wi-day-showers';
    case 350:
      return 'wi-day-sleet';
    case 338:
      return 'wi-day-snow';
    case 335:
      return 'wi-day-snow';
    case 332:
      return 'wi-day-snow';
    case 329:
      return 'wi-day-snow';
    case 326:
      return 'wi-day-snow';
    case 323:
      return 'wi-day-snow';
    case 320:
      return 'wi-day-sleet-storm';
    case 317:
      return 'wi-day-sleet';
    case 314:
      return 'wi-day-rain-mix';
    case 311:
      return 'wi-day-rain-mix';
    case 308:
      return 'wi-day-rain';
    case 305:
      return 'wi-day-rain';
    case 302:
      return 'wi-day-rain';
    case 299:
      return 'wi-day-rain';
    case 296:
      return 'wi-day-showers';
    case 293:
      return 'wi-day-showers';
    case 284:
      return 'wi-day-sleet';
    case 281:
      return 'wi-day-sleet';
    case 266:
      return 'wi-day-showers';
    case 263:
      return 'wi-day-showers';
    case 260:
      return 'wi-day-fog';
    case 248:
      return 'wi-day-fog';
    case 230:
      return 'wi-thunderstorm';
    case 227:
      return 'wi-snow-wind';
    case 200:
      return 'wi-lightning';
    case 185:
      return 'wi-rain-mix';
    case 182:
      return 'wi-sleet';
    case 179:
      return 'wi-snow';
    case 176:
      return 'wi-rain';
    case 143:
      return 'wi-fog';
    case 122:
      return 'wi-cloud';
    case 119:
      return 'wi-cloudy';
    case 116:
      return 'wi-cloud';
    case 113:
      return 'wi-day-sunny';
    default:
      return '';
  }
}
